### ISSUE TITLE
No module named _thread 

### ISSUE THREAD

**Issue by b-madhukar** [vishal-android-freak/firebase-micropython-esp32#7]
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "ufirebase.py", line 7, in <module>
ImportError: no module named '_thread'

**Comment by Belesprit26** [comment]
did you end up with a solution for this.

**Comment by b-madhukar** [comment]
No , I dint find a solution for it, 
I am using " https://github.com/ckoever/micropython-firebase-realtime-database " files to connect firebase for esp32
please check into it

**Comment by Belesprit26** [comment]
Thanks a mil for the assist.
